window.NYS_BUILDER_FALLBACK_DATA = {
  actionsCsv: String.raw`#,Action Title,Action Explanation,Policy,Scope
Unique Identifier,Name of action,Full action language,cross-ref to relevant policies,
alphanumeric,short text,long text,relational link,
A1,Run a Fossil Fuel Nonproliferation Treaty endorsement campaign,"Running a FFNPT campaign in your area is a powerful way to get commitments from local officials on phasing out fossil fuels, which can be used as an accountaibility tool later and a pathway to articulating specifically how they'll phase out. check out this guide on how to run one in your area. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.","P1, P3",subnational
A2,Encourage your Mayor to join the Sustainable Mayors Network,"The Sustainable Mayors Network is a community of practice for local officials to exhange ideas and learn from each others' efforts. It also makes it clear that while our goernment is not acting on climate, there are many people at all levels who are taking climate action. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",,subnational
A3,Set up a Bottle Cap Deposit System,"Pfand systems decrease litering and encourage reuse of materials. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",,national
`,
  policiesCsv: String.raw`#,Policy,Scope,Type,Issue Areas,Commentary,Actions
Unique Identifier,Full policy language,Intl vs Domestic (with subcategories for each),,how handle subcategories?,explanation of / commentary on policy recommendation,cross-ref to relevant actions
alphanumeric,long text,single select,multiselect,multiselect,long text,relational link
P1,"Recognize that achieving a Just Transition(s) is inseparable fromdelivering a just, orderly, and equitable phaseout of fossil fuels in line withkeeping 1.5 degrees within reach. A Just Transition requires ensuringequitable global energy security and committing to fully implement thedecisions and pathways identified in the first Global Stocktake, includingthrough updated NDCs and Just Transition Plans no later than 2026.",International,Just Transition,Energy & Decarbonization,"Ambitious long-term plans may seem unrealistic, but many examples exist where they are already being implemented. For exampls SIDS are... Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",A1
P2,"Establish a mandated dialogue for addressing climate refugees at SB64,further calling upon the UNFCCC, in partnership with the SpecialRapporteur on Human Rights and Climate Change, to create a report fromthe dialogue with recommendations on next steps.",International,Adaptation,Transportation & Mobility,"the UNFCCC has examples of such plans... Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.","A2, A3"
P3,"Rejoin the Paris Agreement, and fulfill their role to act on climate changeas agreed under the UNFCCC.",Domestic,Federal,Transportation & Mobility,"The Paris Agreement and the Paris Group are separate entities. While the US left the Paris Agreement, it did not leave the Paris group... Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",A1
P4,"Deploy statewide multi-hazard early warning systems by 2027 coveringheat, flood, wildfire, and air quality risks with accessible multilingual alertsdelivered through redundant channels (e.g., Maryland, Oregon, Massachusetts,California).",Domestic,Subnational,Agriculture & Food Systems,"Many states already have action plans in place that can serve as a reference point... Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
`
};
